jamesls/fakeredis

README.rst, fakeredis.py, test_fakeredis.py
Adds support for the `hincrbyfloat` operation, raising `ResponseError`s on the same error conditions as redis does through py-redis.
=> Add hincbryfloat operation.

fakeredis.py
=> Throw `TypeError` if `GET` is used against a hash-type

fakeredis.py, test_fakeredis.py
Expire and expireat should return a boolean indicating whether the timeout was successfully set.  In general, this means they return `True` if the specified key exists, `False` otherwise.
=> Fix return value from expire and expireat

.gitignore, fakeredis.py, test_fakeredis.py
redis-py client support command `incrby` which fakeredis not support.
https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L914
=> add method `incrby` for fakeredis

fakeredis.py, test_fakeredis.py
APPEND operation is allowed to missing key. When it has executed, its behaviour works like SET.
=> Support APPEND to not preexisting key

fakeredis.py, test_fakeredis.py
When call method `zadd(name, value, score)` and value is integer, it will lead to raise TypeError zadd() keywords must be strings.
For example:
```
from fakeredis import FakeRedis
f = FakeRedis()
f.zadd('foo', 1, 1)
```
The version 0.6.2 will raise TypeError: zadd() keywords must be strings
=> [Fix bug & fix code style] TypeError: zadd() keywords must be strings when using FakeRedis.

README.rst, fakeredis.py, test_fakeredis.py
I centralized some common logic between `scan`, `hscan`, and `sscan`. I also added the associated "*_iter" methods: `hscan_iter` and `sscan_iter`.
These methods should be fully API-compatible with redis-py, but they are NOT designed to be performant with large data sets, though they should be fine with smaller testing-sized data.
=> Implement hscan and sscan methods

fakeredis.py, test_fakeredis.py
This patch fixes issue #107.
I verified that the tests pass on Windows using Python 3.5 and on OS X using Python 2.7 and Python 3.5.
=> Look for strtod in msvcrt.lib on Windows; test strtod search behavior

fakeredis.py, test_fakeredis.py
The 'true' redis-py library accepts timedeltas for `ex` and `px` parameters; if the expiration is negative, it also throws an exception. 
This pull request fixes these two things to follow redis-py.
=> set() ex and px parameters accept timedelta

fakeredis.py, test_fakeredis.py
This PR adds the `decode_responses` functionality requested in #77, and attempted in #116/#82. 
This implementation is an attempt at adding the required logic without needing to change every method/return-statement. I also wanted this change to be well-tested without rewriting code, so I've written the new test classes using the inheritance pattern already used.
This approach is good because it means internally the library can continue to work with only binary data, and things (*should*) just work. I do see some potential downsides though:
1. Method patching is considered by some to be too *magical* (although for a library whose main purpose is unit-testing, patching is more acceptable)
2. Inheriting the tests this way means there are now 1161 tests :grin:
3. Since binary literals were …
=> Add support for decode_responses

test_fakeredis.py
Without this patch, unit tests is failing on i686:
```
======================================================================
ERROR: test_pttl_should_return_value_for_expiring_key (test_fakeredis.TestFakeRedis)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_2.7/build/test_fakeredis.py", line 2675, in test_pttl_should_return_value_for_expiring_key
self.redis.expire('foo', long_long_c_max)
File "fakeredis.py", line 272, in expire
return self._expire(name, time)
File "fakeredis.py", line 281, in _expire
raise redis.ResponseError("value is not an integer or out of "
ResponseError: value is not an integer or out of range.
====================================================================== …
```
=> Fix unit tests failing on 32 bits CPU archs

fakeredis.py, test_fakeredis.py
Setting a `None` value should be set as the string `'None'`, it was being set as `None` because there's a check for a `None` value in the `to_bytes` function, these checks were removed and a test was added, and all the tests are passing under Python 2 and 3.
=> Fixed setting a None value, it should be set as a string and it was being set as None

fakeredis.py, test_fakeredis.py
This PR fixes a few issues that arise when methods with decoded responses are called within the implementation of a redis command, and then these decoded results are stored without being converted back to bytes.
For example in `sdiffstore()`:
```python
def sdiffstore(self, dest, keys, *args):
"""
Store the difference of sets specified by ``keys`` into a new
set named ``dest``.  Returns the number of keys in the new set.
"""
diff = self.sdiff(keys, *args)
self._db[dest] = diff  # this line is problematic
return len(diff)
```
And just to demo this behaviour:
```python
>>> from fakeredis import FakeStrictRedis
>>> r = FakeStrictRedis(decode_responses=True)
>>> r.sadd('foo', '1', '2')
>>> r.sadd('bar', '2', '3')
>>> r.sdiffstore('baz', 'foo', 'bar')
>>> r.smembers('baz')
{'1'}
>>> …
```
=> Fix bugs related to inconsistent storage of bytes/strings

fakeredis.py
When initializing fake redis with `from_url()`, passing additional parameters like `decode_responses=True` will have no effect, since so far it was ignoring them. This breaks `FakeStrictRedis.from_url()` in python 3.
This PR passes them through to the constructor, like redis-py does:
https://redis-py.readthedocs.io/en/latest/_modules/redis/client.html#StrictRedis.from_url
=> Pass through additional kwargs from `from_url` to the class initializer.

fakeredis.py, test_fakeredis.py
Real `RedisStrict` raises `ResponseError` if you pass it a `float`; `FakeRedisStrict` currently does not. This PR demonstrates a fairly local way of fixing that. I'm happy to expand to make it more general, but I'm not that au fait with Redis' behaviour in general.
=> Make setex fail if passed an unacceptable expiry time type

fakeredis.py, test_fakeredis.py
redis-py allows you to pass `bytes` objects as keys. There are many places where fakeredis does not support that and this patch does not fix all of them, but it at least fixes `sinter` and other methods that use `_list_or_args`.
=> Support b'bytes' keys in `sinter` and similar.

fakeredis.py, test_fakeredis.py
This mimics the behavior of `redis-py`.
=> type('a_bad_key') returns the string 'none', not None

fakeredis.py, test_fakeredis.py
1. setbit SHOULD return old_value instead of None
2. there exists bug when setbit to 0
for example:
```
self.redis.setbit('foo', 4, 0)
value = self.redis.getbit('foo', 4)  # we will get 1, but we should get 0
```
=> fix setbit

fakeredis.py, test_fakeredis.py
Match the function signatures, add support for `value_from_callable`
and `watch_delay` kwargs. Add test for `value_from_callable`.
Fixes #78.
=> Match redis-py's transaction() and pipeline() functions.

fakeredis.py
Because they can get out of sync under python3 since
`_dict` entries are converted into bytes while `_ex_keys` aren't
and `b'foo' != 'foo'` under python 3.
Instead of trying to convert back and forth between `bytes` and `str` in different places,
this new implementation stores everything in `_dict` and
makes sure values and timestamp are always stored together.
=> Remove `_ex_keys` mapping

fakeredis.py, test_fakeredis.py
This extends all the commands that operate on existing data of a specific type to raise a `redis.ResponseError` if the key exists but is not of that type. This fixes #101, but is far more general than #136.
The stricter checking exposed some bugs, so this PR also contains fixes (with unit tests) for #163, #164, #165.
=> Add type checking

fakeredis.py, test_fakeredis.py
It used to call `.encode()` lower down if the type was `str`, which
- if not desirable on Python 2, since bytes == str and the message may
already have been encoded
- does not specify the encoding
- ignores all the other things handled by to_bytes
This partially addresses #146. It does not try to address binary channel
names, but looking at the code for redis-py it's not clear that it fully
supports them either.
=> Use to_bytes to encode publish message

fakeredis.py, test_fakeredis.py
This ensures that no precision is lost when encoding 64-bit floats. This
matches the encoding logic in redis-py. Tests are added for `set`,
`incrbyfloat` and `hincrbyfloat`.
=> Use repr to encode floats in to_bytes

fakeredis.py, test_fakeredis.py
This matches the quirks in the redis pattern matching, which has some
differences from fnmatch. It also applies all the logic in bytes, rather
than the native character encoding.
Fixes #182.
=> Replace fnmatch with hand-coded pattern compiler

fakeredis.py, test_fakeredis.py
There was a missed call to 'subscriber'. The message was also being
encoded to bytes unconditionally rather than being passed through
_normalize; which didn't matter when returning a message (because
responses were patched), but did matter when passing it to a handler.
=> Fix psubscribe with handlers

fakeredis.py, test_fakeredis.py
This is apparently needed on some OSX systems. Closes #188.
=> Add 'System' to the list of libc equivalents

fakeredis.py, test_fakeredis.py
In redis-py, attempting to use __getitem__ with a non-existent key
causes a KeyError to be raised, while fakeredis returns None. This
change makes it so that __getitem__ in fakeredis works the same way as
in redis-py.
Fixes #191
=> Make __getitem__ raise a KeyError for missing keys

fakeredis.py, test_fakeredis.py
=> Supports argument score_cast_func in zrangebyscore()

fakeredis.py, test_fakeredis.py
Upstream Redis Pipeline has a `__len__()` method that causes an empty pipeline to evaluate false-y. This PR adds a similar method to FakeRedis to mimic that behaviour.
=> Align bool/len behaviour of pipeline

.travis.yml, setup.py
Adds Travis config to run tests against Python 3.7.
=> Test on Python 3.7

fakeredis.py, test_fakeredis.py
During eval operation, results of Redis operations returning dictionaries are now passed as Lua tables instead of python lists
This allows for iteration over them within the Lua script.
This is a fix to the error described in issue [204](https://github.com/jamesls/fakeredis/issues/204)
=> Redis operation that returns dict now converted to Lua table when called inside eval operation

fakeredis.py, test_fakeredis.py
During eval operation, KEYS and ARGV are now passed as Lua tables instead of Python lists.
This allows for iteration over them within the Lua script
This is a fix to the error described in issue [204](https://github.com/jamesls/fakeredis/issues/204)
=> eval's KEYS and ARGV are now lua tables

fakeredis.py
In case that a regular expression is specified, it is not needed to copy all the keys if some of them do not match the regular expression.
If a regular expression is not provided, there is no need to iterate over the slice. Instead, we simply copy the entire slice.
This is useful in cases where we're dealing with a large number of keys.
=> Optimize _scan()

fakeredis.py, test_fakeredis.py
=> added pubsub.run_in_thread as it is implemented in redis-py

Pipfile, Pipfile.lock, fakeredis.py, tox.ini
It works out of the box. Only thing is deprecation warnings that are annoying in tests.
Given this: 
https://docs.python.org/3/whatsnew/3.7.html#id3
Getting ABCs from `collections` is depricated in 3.8 so this preemptively fixes that and also get rid of those pesky aforementioned deprecation warnings.
Also adds a Pipfile for those of us who have adopted Pipenv.
=> Python 3.7

fakeredis.py, test_fakeredis.py
Issue #223 
A separate travis-ci run that shows the test first failing without implementation:
https://travis-ci.org/viljoviitanen/fakeredis/builds/452512706
Also to make things sure: I allow my small contribution to be distributed under any licence and assign copyright to current copyright owners.
=> Add __delitem__

.travis.yml, README.rst, fakeredis/__init__.py, fakeredis/_server.py, requirements.txt, setup.py, test_fakeredis.py
Fixes #235 
redis-py 3.2 introduces the new concept of a selector. Herein we introduce a `FakeSelector` which marks our fake connections as always ready. The `FakeSocket` also needs to return an integer from `fileno()` since this will be checked when importing `redis.selector`. 
Let me know if you have any feedback, I've run the full test suite with redis-py 2.10.6, 3.1.0 and 3.2.0. I did not contribute a new test since existing tests fail with 3.2.0.
=> Support for redis-py 3.2 

tox.ini
Travis is already testing using `pypy`. This allows developers to run tests locally using `pypy` too.
=> Add pypy environment for Tox

README.rst, fakeredis/__init__.py, fakeredis/_server.py, test_fakeredis.py, test_fakeredis_hypothesis.py
Note that a separate `_delete` function was written due to the attr manipulation done on `del_` which didn't allow for it to be called directly within unlink.
=> implement unlink command

fakeredis/_server.py, test_fakeredis.py, test_fakeredis_hypothesis.py
Add support for the new `NX`, `XX`, and `CH` flags in the `ZADD` command, which can only be provided with `redis-py` version 3 installed.
This fixes a subset of what's filed in #232. `INCR` flag will be implemented in a different pull request, as it's completely different to handle.
=> Support NX/XX/CH flags in ZADD command

.travis.yml, Pipfile, Pipfile.lock, README.rst, requirements.txt, setup.cfg, test_fakeredis.py, test_fakeredis_hypothesis.py, tox.ini
`nose` is a deprecated project since 2015. Migrate to `pytest`, which will allow to add plugins and improve project's test suite.
=> Migrate project to PyTest

fakeredis/_server.py, test_fakeredis.py
=> Add other inputs for redis connection

fakeredis/_server.py, test_fakeredis.py
Added a very simple `redis.log` Lua call support, wired to the standard python `logging` lib.
Issue #265
=> Lua redis.log implementation

README.rst, requirements.in, requirements.txt, setup.cfg, test/conftest.py, test/test_aioredis.py, test/test_fakeredis.py
I wouldn't try to review everything - there are a *lot* of mechanical changes. Interesting bits are the smaller files and anything with pytest decorators (`@pytest.fixture`, `@pytest.mark`).
=> Make unit tests more pytest-onic

.travis.yml
Pytest + coverage tends to work badly without an editable install, but in general it's preferable to run unit tests against a standard install since that's what users use. So make one case use an editable install for coverage purposes.
=> Fix coverage reports on coveralls.io

fakeredis/_server.py, test/test_fakeredis.py
Add support to `KEEPTTL` flag in the `SET` command which become available in `redis-py` 3.5.0.
=> Implement SET with KEEPTTL

fakeredis/_server.py, test/test_fakeredis.py
Handle indefinite timeout for `PUBSUB` commands.
Indefinite timeout test is disabled for `py-redis` 3.2. This version introduced new default selector based on  `select.poll`, which itself supports indefinite polling via setting the `timeout` to `None`, but `py-redis` in this version scales the `timeout` by 1000 without type checking before passing it to the polling object, which renders this feature unavailable. Affected versions are 3.2.0 and 3.2.1, so the whole 3.2 family.
Fixes #274
=> Handle indefinite timeout for PUBSUB commands

README.rst
I think this documentation is wrong. The new behavior is the same as setting `singleton=False` because that's the flag needed to NOT share data across instances, right?
Looked at the old documentation:
> Alternatively, you can create an instance that does not share data with other instances, by passing singleton=False to the constructor.
=> fixing documentation about previous singleton argument

README.rst, fakeredis/_server.py, test/test_fakeredis.py
I've added support for `SCRIPT EXISTS` and `SCRIPT FLUSH` and wrote tests for the new features. If there's anything you'd like to see changed, I'd be happy to implement those changes.
=> Add support for SCRIPT EXISTS and SCRIPT FLUSH subcommands

README.rst, fakeredis/_server.py, test/test_fakeredis.py
One caveat is that they don't use the RDB format but pickle seemed like a good candidate to mimic what is expected to be an opaque and non-standard format.
https://redis.io/commands/dump
`DUMP key`
> Serialize the value stored at key in a Redis-specific format and return it to the user. The returned value can be synthesized back into a Redis key using the RESTORE command.
> The serialization format is opaque and non-standard, however it has a few semantic characteristics:
> It contains a 64-bit checksum that is used to make sure errors will be detected. The RESTORE command makes sure to check the checksum before synthesizing a key using the serialized value.
Opted for `sha1` here.
> Values are encoded in the same format used by RDB.
This could unfortunately not be achieve as it would be …
=> Add support for DUMP and RESTORE commands.

fakeredis/_server.py, requirements.in, requirements.txt, test/test_fakeredis.py
In Redis 6.0 there's a new option for the SCAN command that allows to limit types of returned keys. This PR adds this option.
=> Add support for TYPE option to SCAN command.

fakeredis/_server.py, test/test_fakeredis.py
As `FakeConnection` is a subclass of the `Connection` class in `redis-py`, in order to honor OOP substitutability principle, the signature of the constructor should be aligned with the one of the base class. That means it should contain at least all the parameters of the base class.
This automatically fixes a problem occurring when the connection object is dynamically instantiated within the context of the default connection pool class in `redis-py`, named `ConnectionPool`, and when, in turn, the latter is dynamically instantiated using its standard `from_url` factory method. In such scenario the instantiation of the connection object fails because the `FakeConnection` class misses both `host` and `port` parameters in its constructor signature.
That happens because the `from_url` factory …
=> Align `FakeConnection` constructor signature to base class

fakeredis/_server.py, test/test_fakeredis.py
It can be called from the garbage collector in the middle of other code
that is holding the server lock, so could deadlock. It now just appends
itself to a cleanup list, and the next command does the cleanup.
Closes #297.
=> Defer the cleanup in FakeSocket.close

MANIFEST.in, fakeredis/__init__.py, fakeredis/aioredis.py, pyproject.toml, setup.cfg, setup.py, test/test_aioredis1.py, test/test_aioredis2.py, test/test_fakeredis.py
- Add a pyproject.toml file (with setuptools_scm, so that pypa-build
will include everything from SCM in the build; and remove MANIFEST.in)
- Move all the metadata from setup.py to setup.cfg (setup.py is left
just to support editable builds).
- Use `attr:` in setup.cfg to get the version programmatically instead
of repeating it.
- Replace distutils.version with packaging.version (the former will be deprecated by PEP 632).
- Update my email address
=> Packaging modernisation

fakeredis/_server.py
random.sample on a set internally casts it to a list, but since Python
3.9 that has been raising a DeprecationWarning. I've explicitly cast to
list myself now.
=> Fix DeprecationWarning for sampling from a set

fakeredis/_server.py
The change of use inspect.signature in #314 broke code that mocks
redis.Redis, because the signature is no longer for the correct
function.
=> Grab the signature of redis.Redis at module import time

.github/workflows/test.yml, fakeredis/_server.py, requirements.txt, setup.cfg, test/test_fakeredis.py, test/test_hypothesis.py
There are a few sorts of changes here:
- new commands (or options on commands) needed because redis-py 4.0 pre-releases depend on them
- other adjustments needed for compatibility with redis-py 4.0 pre-releases.
- tweaks to command behaviour to be compatible with redis 6.2.6 on some corner cases where it behaves differently to 6.0.10.
It doesn't work with redis-py 4.0.0rc1 due to https://github.com/redis/redis-py/issues/1669, but it should be in a much better position once redis-py gets rid of various assumptions of a 6.2 server.
=> Updates to support newer redis and redis-py

fakeredis/_server.py, test/test_fakeredis.py, test/test_hypothesis.py
I needed to implement this after switching to validating against a 6.2
Redis server, because the fuzzer in the hypothesis tests kept testing
that feature by accident.
=> Add support for GET option to SET

fakeredis/_server.py
Popping 0 elements from a list in Redis 6.2.6 is not an error even if
the key is the wrong type. This was correctly implemented for LPOP, but
for RPOP it wasn't done correctly (picked up by hypothesis).
=> Fix an RPOP corner case that only worked for LPOP

fakeredis/_server.py, test/test_fakeredis.py
Since Redis 6.0.7, PERSIST has invalidated watches, and EXPIRE already
did so. Have all changes to the expiry time mark a key as changed.
=> PERSIST and EXPIRE should invalidate watches
